capture:
  window_poll_interval: 0.5
paths:
  data_dir: data
  db_path: data/db.sqlite
  interim_dir: data/interim
  logs_dir: logs
  models_dir: models
  processed_dir: data/processed
  raw_dir: data/raw
base_url: "https://behavior-based-user-management-upload.onrender.com"
project_name: behave
session_label: user1
